matrix:
  include:
    - language: ruby
      rvm: 
        - 2.5.1
      install:
        - gem install jekyll bundler
        - gem install html-proofer
      before_script:
        - bundle install
      script:
        - bundle exec jekyll build
        - bundle exec htmlproofer ./_site --disable-external
      branches:
        only:
          - release
          - master
      env:
        global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
        cache: bundler
        
    - language: node_js
      node_js:
        - "8.10"
      before_install:
        - nvm install 6.1 
      install:
        - npm install -g firebase-tools
      scripts:
        -
  after_success:
    script:
        - firebase deploy --token $FIREBASE_TOKEN
    branches:
      only:
        - release
    
        
          
  

