
language: ruby
node_js:
  - "8.10"
rvm: 
  - 2.5.1
install:
  - npm install -g firebase-tools
  - gem install jekyll bundler
  - gem install html-proofer
before_script:
  - bundle install
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external
branches:
  only:
    - release
    - Develop
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  cache: bundler
deploy:
  provider: firebase
  skip_cleanup: true
  token: 
    env: $FIREBASE_TOKEN
  on:
    branch: release
    
    
        
          
  

